apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotrest-deployment
spec:
  selector:
    matchLabels:
      app: dotrest
  template:
    metadata:
      labels:
        app: dotrest
    spec:
      containers:
        - name: catalog
          image: averyking0/catalog:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: MongoSettings__Host
              value: mongodb-service
            - name: MongoSettings__Password
              valueFrom:
                secretKeyRef:
                  name: dotrest-secrets
                  key: mongodb-password
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80